### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by Mirdin911** [DMagic1/KSP-EVA-Transfer#3] opened 2018-03-26 18:17 UTC
I have KSP 1.4.1.2089 and I tried installing in different ways, however the pipe does not show up anywhere in the game, tried Sandbox mode, career mode, even uninstalled KAS just to make sure, but it seems it does not like my game...

In the config file, the folder names are completely wrong compared to what I have in the game.

MODEL
	{
		model = Squad/Parts/CompoundParts/FuelLine/model
	}	
This is actually model = Squad/Parts/CompoundParts/fuelLine/model (was not fixed with 8.1)
@PART[EVAfuelLine]:FOR[EVATransfer]:NEEDS[VenStockRevamp]
{
    @MODEL 
	{
        @model = VenStockRevamp/Squad/Parts/CompoundParts/FuelPipe
		@texture = model000, VenStockRevamp/Squad/Parts/CompoundParts/Struts_CLR
	}
}
These files or folders in tose locations do not even exist.
My Squad/Part/CompoundParts has 2 folders: fuelLine and strutConnector

Could these be causing the issues?

**Comment by DMagic1** [comment] 2018-03-26 23:43
Duplicate of #2 

Squad changed the folder structure. Upgrading KSP in-place preserves the old folder name, a clean installation results in the new folder name. Use version 8.0 or change the part config if you still have the old version of the fuelLine folder.

**Closed as completed by DMagic1** 2018-03-26 23:43 UTC
